version: "3.9"

services:
  api-gateway:
    build:
      context: ./src/ApiGateway/UtilsGateway
      dockerfile: UtilsGateway/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "8080:8080"
    depends_on:
      - utilsuserservice
      - utilsauthservice

  utilsuserservice:
    build:
      context: ./src/Services/UtilsUserService
      dockerfile: UtilsUserService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__UsersDb: Host=users-db;Port=5432;Database=users;Username=postgres;Password=drowssap
    ports:
      - "5001:8080"
    depends_on:
      - users-db

  utilsauthservice:
    build:
      context: ./src/Services/UtilsAuthService
      dockerfile: UtilsAuthService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "5002:8080"

  users-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: drowssap
    ports:
      - "5432:5432"
    volumes:
      - users_db_data:/var/lib/postgresql/data

volumes:
  users_db_data:
